PREGUNTAS_POR_CATEGORIA = {
"infancia" : [
    "¿Qué juego de tu infancia recuerdas con más cariño y por qué?",
    "¿Qué hábito de tu familia te marcó positivamente?",
    "¿Cuál fue un momento sencillo de la niñez que hoy valoras mucho?",
    "¿Qué te hubiera gustado decirle a tu yo de 10 años?",
    "¿Qué creencia de tu infancia cambiaste al crecer?",
    "¿Cuál era tu juguete favorito y qué significaba para ti?",
    "¿Qué olor te transporta a tu niñez?",
    "¿Qué canción te recuerda a tu infancia?",
    "¿Qué hacías los domingos cuando eras pequeño/a?",
    "¿Quién era tu héroe de la infancia?",
    "¿Qué comida te hacía feliz de niño/a?",
    "¿Qué travesura recuerdas con una sonrisa?",
    "¿Qué maestro/a te marcó en tu infancia?",
    "¿Qué te daba miedo cuando eras pequeño/a?",
    "¿Qué dibujo animado no te perdías?",
    "¿Cómo era tu habitación de niño/a?",
    "¿Qué tradición familiar te encantaba?",
    "¿Qué te hacía sentir seguro/a de pequeño/a?",
    "¿Qué querías ser cuando crecieras?",
    "¿Qué recuerdo tienes de tu primer día de escuela?",
    "¿Qué lugar era tu refugio en la infancia?",
    "¿Qué hacías en vacaciones cuando eras niño/a?",
    "¿Qué juego inventaste con amigos?",
    "¿Qué te hacía reír sin parar?",
    "¿Qué historia familiar te fascinaba?",
    "¿Qué aprendiste de tus abuelos?",
    "¿Qué objeto guardas de tu niñez?",
    "¿Qué te hacía sentir especial?",
    "¿Qué hábito infantil aún conservas?",
    "¿Qué te enseñó tu infancia sobre la amistad?",
    "¿Qué momento te hizo sentir valiente?",
    "¿Qué recuerdo tienes de tus cumpleaños?",
    "¿Qué te gustaba hacer solo/a?",
    "¿Qué te hacía sentir libre?",
    "¿Qué palabra usabas mucho de niño/a?",
    "¿Qué te hacía sentir orgulloso/a?",
    "¿Qué te enseñó tu infancia sobre el amor?",
    "¿Qué te hacía sentir diferente?",
    "¿Qué aprendiste jugando?",
    "¿Qué te hacía sentir frustrado/a?",
    "¿Qué te hacía sentir grande?",
    "¿Qué te hacía sentir pequeño/a?",
    "¿Qué te hacía sentir importante?",
    "¿Qué te hacía sentir invisible?",
    "¿Qué te hacía sentir curioso/a?",
    "¿Qué te hacía sentir confundido/a?",
    "¿Qué te hacía sentir feliz sin razón?",
    "¿Qué te hacía sentir triste sin explicación?",
    "¿Qué te hacía sentir en casa?",
    "¿Qué te hacía sentir lejos?",
    "¿Qué te hacía sentir protegido/a?",
    "¿Qué te hacía sentir inseguro/a?",
    "¿Qué te hacía sentir amado/a?",
    "¿Qué te hacía sentir rechazado/a?",
    "¿Qué te hacía sentir parte de algo?",
    "¿Qué te hacía sentir excluido/a?",
    "¿Qué te hacía sentir creativo/a?",
    "¿Qué te hacía sentir aburrido/a?",
    "¿Qué te hacía sentir emocionado/a?",
    "¿Qué te hacía sentir decepcionado/a?",
    "¿Qué te hacía sentir orgulloso/a de tu familia?",
    "¿Qué te hacía sentir avergonzado/a?",
    "¿Qué te hacía sentir valiente?",
    "¿Qué te hacía sentir cobarde?",
    "¿Qué te hacía sentir fuerte?",
    "¿Qué te hacía sentir débil?",
    "¿Qué te hacía sentir inteligente?",
    "¿Qué te hacía sentir torpe?",
    "¿Qué te hacía sentir especial?",
    "¿Qué te hacía sentir común?",
    "¿Qué te hacía sentir único/a?",
    "¿Qué te hacía sentir igual que los demás?",
    "¿Qué te hacía sentir diferente?",
    "¿Qué te hacía sentir igual?",
    "¿Qué te hacía sentir raro/a?",
    "¿Qué te hacía sentir normal?",
    "¿Qué te hacía sentir feliz en familia?",
    "¿Qué te hacía sentir solo/a?",
    "¿Qué te hacía sentir acompañado/a?",
    "¿Qué te hacía sentir ignorado/a?",
    "¿Qué te hacía sentir escuchado/a?",
    "¿Qué te hacía sentir entendido/a?",
    "¿Qué te hacía sentir incomprendido/a?",
    "¿Qué te hacía sentir seguro/a en casa?",
    "¿Qué te hacía sentir inseguro/a en casa?",
    "¿Qué te hacía sentir feliz en la escuela?",
    "¿Qué te hacía sentir triste en la escuela?",
    "¿Qué te hacía sentir motivado/a?",
    "¿Qué te hacía sentir desanimado/a?",
    "¿Qué te hacía sentir emocionado/a por el futuro?",
    "¿Qué te hacía sentir miedo del futuro?",
    "¿Qué te hacía sentir esperanza?",
    "¿Qué te hacía sentir desesperanza?",
    "¿Qué te hacía sentir alegría por cosas simples?",
    "¿Qué te hacía sentir tristeza por cosas simples?",
    "¿Qué te hacía sentir conectado/a con otros?",
    "¿Qué te hacía sentir desconectado/a?",
    "¿Qué te hacía sentir parte de algo más grande?",
    "¿Qué te hacía sentir pequeño/a en el mundo?",
    "¿Qué te hacía sentir grande en el mundo?",
    "¿Qué te hacía sentir que todo era posible?",
    "¿Qué te hacía sentir que nada era posible?",
    "¿Qué te hacía sentir que eras suficiente?",
    "¿Qué te hacía sentir que no eras suficiente?",
    "¿Qué te hacía sentir que eras amado/a sin condiciones?",
    "¿Qué te hacía sentir que el amor tenía condiciones?",
    "¿Qué te hacía sentir que eras libre?",
    "¿Qué te hacía sentir que estabas atrapado/a?",
    "¿Qué te hacía sentir que eras tú mismo/a?",
    "¿Qué te hacía sentir que debías cambiar?",
    "¿Qué miedos tenías de pequeño?",
    "¿Has tenido alguna experiencia perturbadora en tu infancia?",
    "¿Qué futuro te imaginas para ti mismo/a? ¿Lo has conseguido? Si no, ¿qué crees que ha fallado?"
],

"felices": [
    "¿Qué pequeño detalle del día te da alegría inmediata?",
    "Describe una época en la que te sentiste en ‘flow’. ¿Qué hacías?",
    "¿Qué logro personal te hace sonreír cada vez que lo recuerdas?"
],

"sorprendentes": [
    "¿Qué habilidad rara o inesperada tienes?",
    "¿Cuál ha sido el giro más inesperado de tu vida hasta ahora?",
    "¿Qué creencia impopular sostienes con convicción?",
    "¿Qué detalle de tu vida cotidiana te parece más curioso?",
    "¿Qué experiencia te ha hecho cuestionar tus creencias?",
    "¿Qué creencia de tu infancia cambiaste al crecer?",
    "¿Qué aspecto de tu vida te gustaría entender mejor?"
],

"dolorosas": [
    "¿Qué decepción te enseñó una lección valiosa?",
    "¿Qué límite aprendiste a poner para cuidarte mejor?",
    "¿Qué te ayudó a salir de un momento difícil?",
    "¿Qué estás sanando ahora mismo? (Puedes pasar)",
    "¿Qué creencia limitante has decidido soltar?",
    "¿Qué aspecto de tu vida te gustaría entender mejor?",
    "¿Qué te gustaría explorar más a fondo?",
    "¿Qué te gustaría que la gente entendiera mejor sobre ti?"
],

"valores": [
    "¿Qué valor no negocias y por qué?",
    "¿En qué momento te sentiste auténtico/a recientemente?",
    "¿Qué te gustaría que la gente entendiera mejor sobre ti?",
    "¿Qué aspecto de tu personalidad consideras que es malo y lo cambiarías? ¿Y cuál aún sabiendo que es malo, no cambiarías?"
],

"relaciones": [
    "¿Qué gesto te hace sentir cuidado/a sin fallar?",
    "¿Cómo muestras cariño a tu manera?",
    "¿Qué aprendiste de una relación pasada que hoy cuidas más?",
    "¿Qué significa para ti una ‘buena química’ con alguien?",
    "¿Hay algo que envidies de los demás?"
],

"trabajo": [
    "¿Qué tipo de problemas disfrutas resolver?",
    "¿Qué proyecto te haría levantarte con ilusión cada día?",
    "¿Qué habilidad quieres desarrollar este año y por qué?",
    "¿Qué aspecto de tu trabajo te gustaría entender mejor?"
],

"sexo": [
    "¿Qué te hace sentir más atractivo/a y por qué?",
    "¿Qué prefieres: el cariño en público o la intimidad en privado? ¿Por qué?",
    "¿Qué conversación te ha parecido inesperadamente sexy?",
    "¿Cuál es un límite importante para ti en lo íntimo? (Puedes pasar)",
    "¿Qué detalle de una cita te enciende la curiosidad por conocer más a alguien?",
    "¿Qué te hace sentirte más seguro/a en la intimidad?",
    "¿Sacrificarías tu desgana para complacer a tu pareja?",
    "¿Crees que estás fallando en algo a tu pareja? ¿En qué?"
]}